<form action="<?php echo $this->baseUrl();?>/address/index/edit/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo $this->modId; ?>" method="POST"> 
    <fieldset>
    <legend><?php echo $this->translate("Address details"); ?></legend>
        <table class="fieldsets">
        <?php echo $this->form; ?>
        </table>
    <div class="btnhouse">
        <div class="ltbtns">
                <input type="submit" name="Update" id="Update" value="<?php echo $this->translate("Update"); ?>">
        </div>
        <div class="rtbtns">
                <a href="<?php echo $this->baseUrl();?>/<?php echo $this->path1; ?>/index/commonview/id/<?php echo $this->id; ?>"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
        </div>
    </div>
    </fieldset>
</form>
