<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>KEDB</title>
  <!-- Bootstrap core CSS-->
  
  <link href="<?php  echo $this->baseUrl();?>/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="<?php  echo $this->baseUrl();?>/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="<?php  echo $this->baseUrl();?>/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
  <link href="<?php  echo $this->baseUrl();?>/css/jquery-ui.css" rel="stylesheet">
  <link href="<?php  echo $this->baseUrl();?>/css/kidb.css" rel="stylesheet">

  
  <!-- Custom styles for this template-->
  <link href="css/sb-admin.css" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
	<?php echo $this->render('defaultheader.phtml'); ?>
	</nav>

  <div class="content-wrapper">
   
    <div class="container-fluid">
      <div class="card mb-3">
        <div id="pagecontent">
			<?php echo $this->layout()->content; ?>
		</div>
      </div>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
   
    <!-- Bootstrap core JavaScript-->
    <script type="text/javascript" src="<?php  echo $this->baseUrl();?>/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="<?php  echo $this->baseUrl();?>/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script type="text/javascript" src="<?php  echo $this->baseUrl();?>/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script type="text/javascript" src="<?php  echo $this->baseUrl();?>/vendor/datatables/dataTables.bootstrap4.js"></script>
    <!-- Custom scripts for all pages-->
    <script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/sb-admin.min.js"></script>
	<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/sb-admin-datatables.min.js"></script>

    <!-- Custom scripts for this page-->
	<!-- KEDB -->
	<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/jquery.dataTables.min.js"></script>
	
	<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/kedb.js"></script>
  </div>
</body>

</html>
